version: '3.4'

services:
  sovcombanktest.apiwebapp:
    image: ${DOCKER_REGISTRY-}sovcombanktestapiwebapp
    build:
      context: .
      dockerfile: SovComBankTest.ApiWebApp/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"