name: dotnet package

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore BankService.sln
      - name: Build
        run: dotnet build Bank.ApiWebApp --configuration Release --no-restore
      - name: Cheeck format
        run: dotnet format BankService.sln --verify-no-changes --no-restore -v d
      - name: Test
        run: dotnet test Bank.ModuleTests --no-restore --logger:trx --results-directory "TestResults"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "TestResults"
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
